version: '3.1'

services:
  database:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: IHNNADMIN
    ports:
      - 3306:3306

